### ISSUE TITLE
Load order and async support

### ISSUE THREAD

**Issue by Igor-Lopes** [Neamar/auto-load#16]
Is it possible to specify load order ?

Is there async support for files that should complete a promise first ?

**Comment by Neamar** [comment]
Hello!

There is no way to specify load order, but if you need to load some files first you can autoload twice, for instance:

```js
// Ensure models are loaded first
autoload(__dirname + '/models');
let myFiles = autoload(__dirname);
```

There is no support for asynchronous loading, I'm not sure it would fit into this module TBH!
