### ISSUE TITLE
Adding options

### ISSUE THREAD

**Issue by franciscop** [Neamar/auto-load#5]
I find myself using `auto-load` more and more, and there's a pattern I keep repeating and some options that would make it much more easier as per keeping my code DRY. So I think it'd be nice if `auto-load` would implement options by default. From my past needs, these might be:

| Option       | Default     | Meaning                                                                          |
| ---------------|---------------|----------------------------------------------------------------------------|
| `deep`       | `true`        | Perform a deep recursive search in subfolders as now  |
| `js`             | `true`        | Include javascript files (for fine-tunning)                         |
| `json`         | `true`        | Include json files (for fine-tunning)                                 |

As you can see, they are also backwards compatible as per the defaults and the current functionality. I think that accepting them as the second parameter would be nice:

```js
var controllers = require('auto-load')('controllers', { deep: false, json: false });
```

What do you think of this? Might it be possible within the scope of `auto-load`? I can submit a pull request with the functionality described. Any other options that anyone needs?

***
An alternative would be accepting any random extension like `extensions: ['js', 'json']`, but since this uses `require()` internally and only `js` and `json` can be accepted I thought of only allowing them. However, a case can be made for loading files as strings (for example a `.jade` or a `.txt` as string), so it's worth noting it here. It might be worth another issue as it's extending the current implementation rather than adding options as suggested previously.

**Comment by Neamar** [comment]
I like this!

As you say, even if for now it's not perfect, i think specifying an extension array would be better in case we want to improve the behavior later.

Regarding deep: is it something you need? I have to say I never has this use case ;)

**Comment by franciscop** [comment]
I was trying to request the tests, but I also had a couple of `json` (for testing) which would screw the auto-loader. Then I thought of putting these in a `/data` folder, but even so it would not work with auto-loader for its recursive nature. So I proposed two features that are two ways of solving this problem I was having. I will open a different issue for the extensions and reserve this for *adding options* in general

**Comment by Neamar** [comment]
Made some point in #6,

Seems to me adding js / json flags to auto-load is a good idea (considering them to be true by default). Same thing for the `deep` flag :)
